INSERT INTO city VALUES(1, 'Bucuresti', 'Romania');
INSERT INTO city VALUES(2, 'Iasi', 'Romania');
INSERT INTO city VALUES(3, 'Cluj-Napoca', 'Romania');
INSERT INTO city VALUES(4, 'Oxford', 'UK');
INSERT INTO city VALUES(5, 'Cambridge', 'UK');
INSERT INTO city VALUES(6, 'London', 'UK');
INSERT INTO city VALUES(7, 'Boston', 'USA');
INSERT INTO city VALUES(8, 'New York', 'USA');
INSERT INTO city VALUES(9, 'Zurich', 'Switzerland');
INSERT INTO city VALUES(10, 'Paris', 'France');
INSERT INTO city VALUES(11, 'Berlin', 'Germany');

INSERT INTO club VALUES(1, 'Clubul Sportiv Fotbal', 'Fotbal', 'Strada Universitatii, nr. 1');
INSERT INTO club VALUES(2, 'Clubul de Volei', 'Volei', 'Strada Unirii, nr. 2');
INSERT INTO club VALUES(3, 'Clubul de Tenis', 'Tenis', 'Strada Eternitatii, nr. 3');
INSERT INTO club VALUES(4, 'Clubul de Baschet', 'Baschet', 'Strada Libertatii, nr. 4');
INSERT INTO club VALUES(5, 'Clubul de Handbal', 'Handbal', 'Strada Independentei, nr. 5');
INSERT INTO club VALUES(6, 'Clubul de Rugby', 'Rugby', 'Strada Unirii, nr. 6');
INSERT INTO club VALUES(7, 'Clubul de Sah', 'Sah', 'Strada Libertatii, nr. 7');
INSERT INTO club VALUES(8, 'Clubul de Istorie', 'Istorie', 'Strada Universitatii, nr. 8');
INSERT INTO club VALUES(9, 'Clubul de Matematica', 'Matematica', 'Strada Eternitatii, nr. 9');
INSERT INTO club VALUES(10, 'Clubul de Informatica', 'Informatica', 'Strada Unirii, nr. 10');
INSERT INTO club VALUES(11, 'Clubul de jmecheri', 'Informatica', 'Strada Libertatii, nr. 11');
INSERT INTO club VALUES(12, 'Clubul de programatori', 'Informatica', 'Strada Universitatii, nr. 12');
INSERT INTO club VALUES(13, 'Clubul de hackathoane', 'Informatica', 'Strada Eternitatii, nr. 13');

INSERT INTO university VALUES(1, 'Universitatea Politehnica Bucuresti', 'Engineering', TO_DATE('1920-06-10', 'YYYY-MM-DD'), 1);
INSERT INTO university VALUES(2, 'Facultatea de Matematica si Informatica', 'Computer Science', TO_DATE('1878-02-21', 'YYYY-MM-DD'), 1);
INSERT INTO university VALUES(3, 'Facultatea de Drept', 'Law',  TO_DATE('1783-04-06', 'YYYY-MM-DD'), 1);
INSERT INTO university VALUES(4, 'Universitatea Alexandru Ioan Cuza', 'Computer Science', TO_DATE('1860-01-01', 'YYYY-MM-DD'), 2);
INSERT INTO university VALUES(5, 'University of Oxford', 'Science', TO_DATE('1096-02-19', 'YYYY-MM-DD'), 4);
INSERT INTO university VALUES(6, 'University of Cambridge', 'Science', TO_DATE('1209-02-19', 'YYYY-MM-DD'), 5);
INSERT INTO university VALUES(7, 'Harvard University', 'Science', TO_DATE('1636-02-19', 'YYYY-MM-DD'), 7);
INSERT INTO university VALUES(8, 'Massachusetts Institute of Technology', 'Science', TO_DATE('1861-02-19', 'YYYY-MM-DD'), 7);
INSERT INTO university VALUES(9, 'University of Zurich', 'Science', TO_DATE('1833-02-19', 'YYYY-MM-DD'), 9);
INSERT INTO university VALUES(10, 'University of Paris', 'Science', TO_DATE('1150-02-19', 'YYYY-MM-DD'), 10);
INSERT INTO university VALUES(11, 'University of Berlin', 'Law', TO_DATE('1809-02-19', 'YYYY-MM-DD'), 11);
INSERT INTO university VALUES(12, 'University of London', 'Medicine', TO_DATE('1836-02-19', 'YYYY-MM-DD'), 6);
INSERT INTO university VALUES(13, 'University of New York', 'Medicine', TO_DATE('1831-02-19', 'YYYY-MM-DD'), 8);
INSERT INTO university VALUES(14, 'Carol Davila', 'Medicine and Pharmacy', TO_DATE('1636-02-19', 'YYYY-MM-DD'), 1);

INSERT INTO department VALUES(1, '131', 'fb_group_131', 'wapp_group_131');
INSERT INTO department VALUES(2, '132', 'fb_group_132', 'wapp_group_132');
INSERT INTO department VALUES(3, '133', 'fb_group_133', 'wapp_group_133');
INSERT INTO department VALUES(4, '134', 'fb_group_134', 'wapp_group_134');
INSERT INTO department VALUES(5, '141', 'fb_group_141', 'wapp_group_141');
INSERT INTO department VALUES(6, '142', 'fb_group_142', 'wapp_group_142');
INSERT INTO department VALUES(7, '143', 'fb_group_143', 'wapp_group_143');
INSERT INTO department VALUES(8, '144', 'fb_group_144', 'wapp_group_144');
INSERT INTO department VALUES(9, '151', 'fb_group_151', 'wapp_group_151');
INSERT INTO department VALUES(10, '152', 'fb_group_152', 'wapp_group_152');
INSERT INTO department VALUES(11, '231', 'fb_group_231', 'wapp_group_231');
INSERT INTO department VALUES(12, '232', 'fb_group_232', 'wapp_group_232');
INSERT INTO department VALUES(13, '233', 'fb_group_233', 'wapp_group_233');
INSERT INTO department VALUES(14, '234', 'fb_group_234', 'wapp_group_234');
INSERT INTO department VALUES(15, '241', 'fb_group_241', 'wapp_group_241');
INSERT INTO department VALUES(16, '242', 'fb_group_242', 'wapp_group_242');
INSERT INTO department VALUES(17, '243', 'fb_group_243', 'wapp_group_243');
INSERT INTO department VALUES(18, '244', 'fb_group_244', 'wapp_group_244');
INSERT INTO department VALUES(19, '251', 'fb_group_251', 'wapp_group_251');
INSERT INTO department VALUES(20, '252', 'fb_group_252', 'wapp_group_252');

INSERT INTO course VALUES(1, 'Algebra', 5, 'Examen');
INSERT INTO course VALUES(2, 'Analiza', 2, 'Examen');
INSERT INTO course VALUES(3, 'Geometrie', 3, 'Examen');
INSERT INTO course VALUES(4, 'Logica', 4, 'Examen');
INSERT INTO course VALUES(5, 'Baze de date', 3, 'Proiect');
INSERT INTO course VALUES(6, 'Gandire critica', 1, 'Proiect');
INSERT INTO course VALUES(7, 'LFA', 5, 'Examen');
INSERT INTO course VALUES(8, 'OOP', 4, 'Examen');
INSERT INTO course VALUES(9, 'DAW', 2, 'Proiect');
INSERT INTO course VALUES(10, 'SGBD', 3, 'Proiect');
INSERT INTO course VALUES(11, 'TW', 4, 'Proiect');
INSERT INTO course VALUES(12, 'GAL', 3, 'Examen');
INSERT INTO course VALUES(13, 'PAO', 4, 'Examen');

INSERT INTO final_project VALUES(1, 'Crowd knowledge contribution', 'Alexe Bogdan', TO_DATE('2018-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(2, 'Digital school groups', 'Boriga Radu', TO_DATE('2019-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(3, 'Micro-social platform', 'Paun Andrei', TO_DATE('2022-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(4, 'Open discussion', 'Drobrovat Anca', TO_DATE('2018-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(5, 'Social bookmarking', 'Ionescu Radu', TO_DATE('2019-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(6, 'Online shop', 'Cimpean Iulian', TO_DATE('2022-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(7, 'Task management', 'Alexe Bogdan', TO_DATE('2022-06-10', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(8, 'Music platform', 'Bill Gates', TO_DATE('2022-03-23', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(9, 'Video platform', 'Klaus Iohannis', TO_DATE('2023-02-18', 'YYYY-MM-DD'));
INSERT INTO final_project VALUES(10, 'Audio platform', 'Joe Biden', TO_DATE('2023-01-02', 'YYYY-MM-DD'));

INSERT INTO student VALUES(1, 'Robert', 'Trifan', 20, 2, 20, 3);
INSERT INTO student VALUES(2, 'Alexandru', 'Pascu', 20, 2, 20, 7);
INSERT INTO student VALUES(3, 'Anna', 'Pecheanu', 18, 1, 10, 4);
INSERT INTO student VALUES(4, 'Albert', 'Balauta', 20, 1, 9, 2);
INSERT INTO student VALUES(5, 'Radu', 'Nedelcu', 19, 2, 19, 1);
INSERT INTO student VALUES(6, 'Tudor', 'Haulica', 19, 2, 18, 5);
INSERT INTO student VALUES(7, 'Andrei', 'Murica', 18, 1, 2, 6);
INSERT INTO student VALUES(8, 'Radu', 'Pop', 21, 2, 20, 8);
INSERT INTO student VALUES(9, 'Cornel', 'Frunza', 20, 1, 19, 9);
INSERT INTO student VALUES(10, 'Gigel', 'Gheorghe', 19, 2, 18, 10);

INSERT INTO student_club VALUES(1, 11);
INSERT INTO student_club VALUES(2, 1);
INSERT INTO student_club VALUES(3, 3);
INSERT INTO student_club VALUES(4, 1);
INSERT INTO student_club VALUES(5, 6);
INSERT INTO student_club VALUES(6, 4);
INSERT INTO student_club VALUES(1, 1);
INSERT INTO student_club VALUES(2, 9);
INSERT INTO student_club VALUES(3, 9);
INSERT INTO student_club VALUES(4, 13);
INSERT INTO student_club VALUES(5, 12);
INSERT INTO student_club VALUES(6, 8);
INSERT INTO student_club VALUES(1, 7);
INSERT INTO student_club VALUES(2, 5);
INSERT INTO student_club VALUES(3, 2);
INSERT INTO student_club VALUES(4, 10);
INSERT INTO student_club VALUES(5, 5);
INSERT INTO student_club VALUES(6, 3);

INSERT INTO professor VALUES(1, 'Bogdan', 'Alexe', 30, 10);
INSERT INTO professor VALUES(2, 'Radu', 'Boriga', 45, 20);
INSERT INTO professor VALUES(3, 'Andrei', 'Paun', 40, 7);
INSERT INTO professor VALUES(4, 'Anca', 'Drobrovat', 35, 5);
INSERT INTO professor VALUES(5, 'Radu', 'Ionescu', 35, 12);
INSERT INTO professor VALUES(6, 'Iulian', 'Cimpean', 30, 8);
INSERT INTO professor VALUES(7, 'Laurentiu', 'Leustean', 60, 30);
INSERT INTO professor VALUES(8, 'Iulia', 'Hirica', 55, 35);
INSERT INTO professor VALUES(9, 'Cezara', 'Benegui', 27, 3);
INSERT INTO professor VALUES(10, 'Marius', 'Dumitran', 37, 12);

INSERT INTO professor_course VALUES(1, 4);
INSERT INTO professor_course VALUES(2, 7);
INSERT INTO professor_course VALUES(3, 2);
INSERT INTO professor_course VALUES(4, 1);
INSERT INTO professor_course VALUES(5, 3);
INSERT INTO professor_course VALUES(6, 10);
INSERT INTO professor_course VALUES(7, 11);
INSERT INTO professor_course VALUES(8, 5);
INSERT INTO professor_course VALUES(9, 6);
INSERT INTO professor_course VALUES(10, 8);
INSERT INTO professor_course VALUES(1, 2);
INSERT INTO professor_course VALUES(2, 10);
INSERT INTO professor_course VALUES(3, 6);
INSERT INTO professor_course VALUES(4, 7);
INSERT INTO professor_course VALUES(5, 3);
INSERT INTO professor_course VALUES(6, 2);
INSERT INTO professor_course VALUES(7, 1);
INSERT INTO professor_course VALUES(8, 4);
INSERT INTO professor_course VALUES(9, 5);
INSERT INTO professor_course VALUES(10, 5);

INSERT INTO student_course VALUES(1, 5);
INSERT INTO student_course VALUES(2, 9);
INSERT INTO student_course VALUES(3, 11);
INSERT INTO student_course VALUES(4, 1);
INSERT INTO student_course VALUES(5, 7);
INSERT INTO student_course VALUES(6, 3);
INSERT INTO student_course VALUES(1, 10);
INSERT INTO student_course VALUES(2, 6);
INSERT INTO student_course VALUES(3, 2);
INSERT INTO student_course VALUES(4, 8);
INSERT INTO student_course VALUES(5, 4);
INSERT INTO student_course VALUES(6, 11);
INSERT INTO student_course VALUES(1, 2);
INSERT INTO student_course VALUES(2, 8);
INSERT INTO student_course VALUES(7, 11);
INSERT INTO student_course VALUES(2, 10);
INSERT INTO student_course VALUES(5, 8);
INSERT INTO student_course VALUES(5, 9);
INSERT INTO student_course VALUES(10, 12);

INSERT INTO student_university VALUES(1, 8);
INSERT INTO student_university VALUES(2, 3);
INSERT INTO student_university VALUES(3, 5);
INSERT INTO student_university VALUES(4, 14);
INSERT INTO student_university VALUES(5, 7);
INSERT INTO student_university VALUES(6, 9);
INSERT INTO student_university VALUES(1, 9);
INSERT INTO student_university VALUES(2, 5);
INSERT INTO student_university VALUES(3, 13);
INSERT INTO student_university VALUES(4, 12);
INSERT INTO student_university VALUES(5, 2);
INSERT INTO student_university VALUES(6, 10);
INSERT INTO student_university VALUES(7, 11);
INSERT INTO student_university VALUES(1, 1);
INSERT INTO student_university VALUES(2, 4);
INSERT INTO student_university VALUES(3, 6);
INSERT INTO student_university VALUES(4, 7);
INSERT INTO student_university VALUES(5, 8);
INSERT INTO student_university VALUES(6, 11);
INSERT INTO student_university VALUES(7, 12);

COMMIT;
ROLLBACK;